ArcLive/ArcLive/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


#プロジェクト全体のルーティング
#path以降は含めたいアプリケーションのルーティングを記載
#例：records/に対してrecords.urlsを紐づけているので、records/を加えるとそのページにアクセス可能になる
urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),  # 127.0.0.1:8000/admin/
    path('', include('django.contrib.auth.urls')),
    path('records/', include('records.urls')),
    
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ArcLive/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views


app_name = "accounts"

urlpatterns = [
    path('login/', LoginView.as_view(), name= 'login'),
    path('logout/', LogoutView.as_view(), name= 'logout'),
    path('mypage/', views.mypage, name="mypage"),
    path('change_email/', views.change_email, name="change_email"),
    path('change_password/', views.change_password, name="change_password"),
    path('signup/', views.signup, name="signup"),
    # パスワード再発行フォーム
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'), 
    # パスワード再発行メール送信完了
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # パスワード再設定
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # パスワード再設定完了
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

ArcLive/records/urls.py
from django.urls import path
from . import views


app_name = 'records'
urlpatterns = [
        path("record/home", views.home, name='home'), #1つ目のURLを通ったらviews.homeを動かすようにする。このURLの名前はhomeという意味
        path("record/create/", views.record_create, name='record_create'),
        path("record/list/", views.record_list, name='record_list'),
        path("record/<uuid:pk>/", views.record_edit, name="record_edit"),
        path("record/<uuid:pk>/update/", views.record_update, name="record_update"),
        path("record/<uuid:pk>/delete/", views.record_delete, name="record_delete"),
        
    ]
    

ArcLive/templates/base/arclive_base.html
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>ArcLive</title>
        {% bootstrap_css %}
        {% bootstrap_javascript %}
    </head>
    <body>
        <h1>ArcLive&#127928;</h1>
        {% block body %}
        {% endblock %}
    </body>
</html>

ArcLive/templates/base/base.html
{% load static %}
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <title>ArcLive&#127928;</title>
        {% bootstrap_css %}
        <link rel="stylesheet" href="{% static 'base/base.css' %}">
        
    </head>
    <!-- 以下が画面に表示される-->
    <body>
        <header>ArcLive&#127928;</header>
        <main>
            {% block main %}
            {% endblock %}
        </main>
        <footer>
            <div>
                <input id="image_home"; type="radio"; style="display:none"; value="image_home.png"; name="image">
                <label for="image_home">
                    <a href="{% url 'records:home'%}">
                        <img src="/media/footer/home.png">
                    </a>
                </label>
        
                <input id="image_plus" type="radio" style="display:none"; value="image_plus.png" name="image">
                <label for="image_plus">
                    <a href="{% url 'records:record_create' %}">
                        <img src="/media/footer/onnpu.png">
                    </a>
                </label>
                
                <input id="image_document" type="radio" style="display:none"; value="image_document.png" name="image">
                <label for="image_document">
                    <a href="{% url 'records:record_list'%}">
                        <img src="/media/footer/document.png">
                    </a>
                </label>
                
                <input id="image_account" type="radio" style="display:none"; value="image_account.png" name="image">
                <label for="image_account">
                    <a href="{% url 'accounts:mypage'%}">
                        <img src="/media/footer/account.png">
                    </a>
                </label>
            </div>
           
        </footer>
            {% bootstrap_javascript %}
    </body>
</html>