ArcLive/ArcLive/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


#プロジェクト全体のルーティング
#path以降は含めたいアプリケーションのルーティングを記載
#例：records/に対してrecords.urlsを紐づけているので、records/を加えるとそのページにアクセス可能になる
urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),  # 127.0.0.1:8000/admin/
    path('', include('django.contrib.auth.urls')),
    path('records/', include('records.urls')),
    
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ArcLive/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views


app_name = "accounts"

urlpatterns = [
    path('login/', LoginView.as_view(), name= 'login'),
    path('logout/', LogoutView.as_view(), name= 'logout'),
    path('mypage/', views.mypage, name="mypage"),
    path('change_email/', views.change_email, name="change_email"),
    path('change_password/', views.change_password, name="change_password"),
    path('signup/', views.signup, name="signup"),
    # パスワード再発行フォーム
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'), 
    # パスワード再発行メール送信完了
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # パスワード再設定
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # パスワード再設定完了
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

ArcLive/accounts/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractUser
import uuid


class UserManager(BaseUserManager):
    def create_user(self, email, password=None):
        """
        #Creates and saves a User with the given email, password
        """
        
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        """
        Creates and saves a superuser with the given email,password.
        """
        user = self.create_user(
            email,
            password=password,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractUser):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    email = models.EmailField(max_length=254, unique=True)
    username = None
    first_name =None
    last_name = None
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.id}|{self.email}"
    
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []
    objects = UserManager()


class Preset_Image(models.Model):
    preset_image_url = models.ImageField(verbose_name='アプリ内画像',upload_to="account/preset/")
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True) 
    def __str__(self):
        return f"{self.preset_image_url}"
    


class User_Image(models.Model):
    user_id = models.ForeignKey('User', on_delete=models.CASCADE,verbose_name='ユーザーID')
    user_image_url = models.ImageField(blank=True, null=True,verbose_name='ユーザーの本体の画像URL',upload_to="account/user/")
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

ArcLive/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('email',)

ArcLive/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy
from django.contrib import messages
from .forms import CustomUserCreationForm
from django.views import generic
from django.contrib.auth import views as auth_view

class SignupView(generic.CreateView):
    form_class = CustomUserCreationForm
    template_name ='accounts/signup.html'
    success_url = reverse_lazy('/login/')


class MypageView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'accounts/mypage.html')
    
    
class ChangeEmailView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'accounts/change_email.html', {"user": request.user})
    
    def post(self,request):
        new_email = request.POST.get('email')
        request.user.email = new_email
        request.user.save()
        
        #メールアドレス変更後にメッセージを表示
        messages.success(request, 'メールアドレスを変更しました')
        return redirect ('accounts:mypage')
    

class PasswordChangeView(LoginRequiredMixin, PasswordChangeView):
    template_name = "accounts/change_password.html"
    success_url = reverse_lazy("accounts:mypage")
    
    #パスワード変更後にメッセージを表示
    def form_valid(self, form):
        messages.success(self.request, 'パスワードを変更しました')
        return super().form_valid(form)

        
    
    

mypage = MypageView.as_view()
change_email = ChangeEmailView.as_view()
change_password = PasswordChangeView.as_view()
signup = SignupView.as_view()

ArcLive/templates/accounts/change_email.html
{% extends "base/base.html" %}
{% block main %}
<div style="text-align: center";>
    <h4>メールアドレス変更<h4>
    <form method="post">
        {% csrf_token %}
        <p>現在のメールアドレス: {{user.email }}</p>
        <label>新しいメールアドレス</label>
        <br>
        <input type="email" name="new_email" value="{{ user.email }}"required>
        <br>
        <br>
        <button type="submit">変更</button>
    </form>

</div>
{% endblock %}

ArcLive/templates/accounts/change_password.html
{% extends "base/base.html" %}
{% block main %}
<div class="container" style="text-align: center; padding: 20px;">
    <h4>パスワード変更<h4>
    <form method="post">
        {% csrf_token %}
        
        <div style="text-align: left; display:inline-block; margin-bottom: 20px ;>
            {{ form.as_p }}
        </div>
        <p>
        <button type="submit">更新</button>
        
        
    </form>
</div>
{% endblock %}

ArcLive/templates/accounts/index.html
{% extends "base/arclive_base.html" %}
{% block body%}

<p>{{ datetime_now }}</p>
<br>
<a href="{% url '' % }">リンク先のページに飛ぶ</a>
<br>
<a href="{% url 'accounts:logout' % }" method="post">
    {% csrf_token %}
    <buttun type="submit">ログアウト</buttun>
</form>
{% endblock%}

ArcLive/templates/accounts/mypage.html
{% extends "base/base.html" %}
{% block main %}
    <h4>マイページ<h4>
        {% if messages %}
            {% for messages in messages %}
                <div style="color; #4b4b4b; padding: 10px; margin_bottom: 20px; ">
                    {{ messages }}
            {% endfor %}
        {% endif %}

        <div style="margin: 20px 0; ">
            <label>メールアドレス</label>
            <br>
            <input type="text" value="{{ user.email }}" readonly>
            <button type="submit"><a href="{% url 'accounts:change_email'%}">変更</a></button>
        </div>

        <div style="margin: 20px 0; ">
            <label>パスワード</label>
            <br>
            <input type="password" value="********" readonly>
            <button type="submit"><a href="{% url 'accounts:change_password'%}">変更</a></button>
        </div>

    <form action="{% url 'accounts:logout' %}" method="post">
        {% csrf_token %}
        <button type="submit",
        style="color:#ffffff; border: none; padding: 10px 20px; border-radius:5px">
            ログアウト</button>
    </form>

{% endblock %}

ArcLive/templates/accounts/signup.html
{% extends "base/arclive_base.html" %}
{% block body %}
<h4>新規アカウント登録<h4>

<form method="post" style="display: inline-block; text-align: left; background: rgba(255, 255, 255, 0.1); padding 30px; border-radius: 10px">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">登録</button>
</form>
<p style="margin_top: 20px;">
    <a href="{% url 'login' %}" style="color:#add8e6; text-decoration: none;">ログイン画面に戻る</a>
</p>

{% endblock %}